# Generated by Django 3.2.16 on 2023-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='color',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six')], default='two', max_length=255, null=True),
        ),
    ]
