# Generated by Django 3.2.16 on 2023-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_skills_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='demoLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
