# Generated by Django 3.2.16 on 2023-04-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_projects_demolink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='twitter',
            new_name='whatsapp',
        ),
    ]
